apiVersion: v1
kind: Service
metadata:
  name: simple-blog
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
    - port: 443
      name: https
      targetPort: http
  selector:
    app.kubernetes.io/name: simple-blog
    process: web