apiVersion: v1
kind: Service
metadata:
  name: simple-blog
spec:
  ports:
    - port: 80
      targetPort: http
    - port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: simple-blog
    process: web