# Name of your application. Used to uniquely configure containers.
service: simple-blog

# Name of the container image.
image: junkers21/simple-blog-mrsk

# Deploy to these servers.
servers:
  web:
    hosts:
      # set to the public ip of the host
      - 134.209.240.208
    options:
      add-host: host.docker.internal:host-gateway

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: junkers21
  # Always use an access token rather than real password when possible.
  password:
    - MRSK_REGISTRY_PASSWORD

env:
  clear:
    REDIS_URL: "redis://host.docker.internal:6379/0"
    MYSQL_HOST: "host.docker.internal"

# Use a different ssh user than root
# ssh:
#   user: app

# Configure builder setup.
# builder:
#   args:
#     RUBY_VERSION: 3.2.0
#   secrets:
#     - GITHUB_TOKEN
#   remote:
#     arch: amd64
#     host: ssh://app@192.168.0.1

# Use accessory services (secrets come from .env).
accessories:
  db:
    image: mysql:8.0
    host: 134.209.240.208
    port: "172.17.0.1:3306:3306"
    env:
      secret:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_PASSWORD
        - MYSQL_USER
    directories:
      - data:/var/lib/mysql
  redis:
    image: redis:7.0
    host: 134.209.240.208
    port: "172.17.0.1:6379:6379"
    directories:
      - data:/data

# Configure custom arguments for Traefik
# traefik:
#   args:
#     accesslog: true
#     accesslog.format: json

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /up
  port: 3000
  max_attempts: 10
  interval: 20s
