name: Build And Push To Registry
on:
  push:
    branches:
      - release/docker
      - release/kubernetes
jobs:
  deploy_to_kubernetes:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig Production
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-1-27-2-do-0-fra1-1689508975529

      - name: Delete ghcr secret
        run: kubectl delete secret ghcr-login-secret

      - name: Setup ghcr secret
        run: kubectl create secret docker-registry ghcr-login-secret --docker-server=ghcr.io --docker-username=${{ secrets.GHRC_USER }} --docker-password=${{ secrets.GHRC_PAT }} --docker-email=${{ secrets.GHRC_EMAIL }}

      - name: Kubernetes rollout the latest image
        run: kubectl apply -f $GITHUB_WORKSPACE/.k8s

      - name: Verify deployment
        run: kubectl rollout status deployment/simple-blog-web
