name: Build And Push To Registry
on:
  push:
    branches:
      - release/mrsk
jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: set ssh
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519

      - name: set env file
        run: |
          echo "RAILS_MASTER_KEY= ${{ secrets.RAILS_MASTER_KEY }}" >> .env
          echo "MRSK_REGISTRY_PASSWORD= ${{ secrets.CR_PAT }}" >> .env

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u junkers21 --password-stdin

      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/junkers21/simple-blog-mrsk:${{ github.sha }}, ghcr.io/junkers21/simple-blog-mrsk:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Ruby setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: MRSK deploy
        run: |
          gem install mrsk
          mrsk deploy -vvvv --skip_push
