name: Build And Push To Registry
on:
  push:
    branches:
      - release/docker
jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u junkers21 --password-stdin
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "ghcr.io/junkers21/simple_blog_ror:latest"
