name: Build And Push To Registry
on:
  push:
    branches:
      - release/docker
jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v2

      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.2.1'

      - name: set env file
        run: |
          echo "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" >> .env
          echo "MRSK_REGISTRY_PASSWORD=${{ secrets.CR_PAT }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "RAILS_ENV=production" >> .env
          echo "DOCKER_BUILDKIT=1" >> .env

      - name: MRSK
        run: |
          gem install mrsk
          mrsk deploy